//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SaveMe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_SaveMeTrackerEntities : DbContext
    {
        public db_SaveMeTrackerEntities()
            : base("name=db_SaveMeTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<DailyExpense> DailyExpenses { get; set; }
        public virtual DbSet<LoginDetail> LoginDetails { get; set; }
        public virtual DbSet<MonthlySaving> MonthlySavings { get; set; }
        public virtual DbSet<RemoteWeeklyExpenseDetail> RemoteWeeklyExpenseDetails { get; set; }
        public virtual DbSet<TotalSaving> TotalSavings { get; set; }
        public virtual DbSet<UserData> UserDatas { get; set; }
        public virtual DbSet<WeeklyExpenseDetail> WeeklyExpenseDetails { get; set; }
        public virtual DbSet<WeeklySaving> WeeklySavings { get; set; }
    }
}
