//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SaveMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDetail
    {
        public int LoginDetailsID { get; set; }
        public int UserDataID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModiﬁed { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
