//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SaveMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteWeeklyExpenseDetail
    {
        public int RemoteWeeklyExpenseDetailsID { get; set; }
        public int UserDataID { get; set; }
        public int CategoryID { get; set; }
        public int WeeklyExpenseDetailsID { get; set; }
        public decimal Amount { get; set; }
        public int UpdatedWeek { get; set; }
        public int UpdatedMonth { get; set; }
        public int UpdatedYear { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModiﬁed { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual UserData UserData { get; set; }
        public virtual WeeklyExpenseDetail WeeklyExpenseDetail { get; set; }
    }
}
